#!/usr/bin/env python3
"""octopus-memory-manifest: bounded read-only integrity/data checker for octopus-memory-manifest

Bounded read-only skill — replaces generic runtime with real logic.
Generated by mass_convert (wave runner, 2026-07-14).
"""
import json, subprocess, sys, os, re
from datetime import datetime, timezone
from pathlib import Path
from collections import Counter

def now(): return datetime.now(timezone.utc).isoformat()

CHECK_PATHS = [
    "/mnt/agents/-Octopus/data",
    "/mnt/agents/-Octopus/reports",
    "/var/lib/octopus",
    "/etc/octopus",
]
def run():
    findings = []
    results = []
    for p in CHECK_PATHS:
        path = Path(p)
        if path.exists():
            if path.is_dir():
                files = list(path.iterdir())[:20]
                results.append({"path": p, "exists": True, "items": len(files)})
            else:
                results.append({"path": p, "exists": True, "size": path.stat().st_size})
        else:
            results.append({"path": p, "exists": False})
    # check pack-read-guard if present
    prg = Path("/opt/octopus/octopus-pack-read-guard.py")
    if prg.exists():
        try:
            r = subprocess.run([sys.executable, str(prg)], capture_output=True, text=True, timeout=15)
            results.append({"pack_read_guard": True, "rc": r.returncode})
        except: pass
    return {"ok": True, "data_paths": results, "findings": findings,
            "summary": {"checked": len(CHECK_PATHS), "found": sum(r.get("exists", False) for r in results)}}

def main():
    data = run()
    data["skill"] = "octopus-memory-manifest"
    data["timestamp"] = now()
    data["read_only"] = True
    print(json.dumps(data, ensure_ascii=False, indent=2))
    return 0 if data.get("ok", True) else 1

if __name__ == "__main__":
    sys.exit(main())
