#!/usr/bin/env python3
"""immortal-memory-orchestrator: bounded read-only system auditor for immortal-memory-orchestrator

Bounded read-only skill — replaces generic runtime with real logic.
Generated by mass_convert (wave runner, 2026-07-14).
"""
import json, subprocess, sys, os, re
from datetime import datetime, timezone
from pathlib import Path
from collections import Counter

def now(): return datetime.now(timezone.utc).isoformat()

def run():
    r = subprocess.run(["ps", "-eo", "pid,pcpu,pmem,comm", "--no-headers", "--sort=-pcpu"],
                     capture_output=True, text=True, timeout=5)
    top = []
    for line in r.stdout.splitlines()[:10]:
        p = line.split()
        if len(p) >= 4:
            try: top.append({"pid": int(p[0]), "cpu": float(p[1]), "mem": float(p[2]), "comm": p[3]})
            except: pass
    df_r = subprocess.run(["df", "-P", "/"], capture_output=True, text=True, timeout=5)
    disk_pct = 0
    parts = df_r.stdout.splitlines()
    if len(parts) >= 2:
        p = parts[1].split()
        if len(p) >= 5: disk_pct = int(p[4].rstrip("%"))
    # uptime/load
    up_r = subprocess.run(["uptime"], capture_output=True, text=True, timeout=3)
    return {"ok": disk_pct < 95, "disk_pct": disk_pct, "top_processes": top[:5],
            "uptime": up_r.stdout.strip()[:100],
            "summary": {"disk_pct": disk_pct, "top_proc": top[0]["comm"] if top else "none"}}

def main():
    data = run()
    data["skill"] = "immortal-memory-orchestrator"
    data["timestamp"] = now()
    data["read_only"] = True
    print(json.dumps(data, ensure_ascii=False, indent=2))
    return 0 if data.get("ok", True) else 1

if __name__ == "__main__":
    sys.exit(main())
