"""Canonical lifecycle event names for the vNext runtime."""

EXECUTION_STARTED = "execution.started"
EXECUTION_COMPLETED = "execution.completed"
EXECUTION_FAILED = "execution.failed"
PLAN_CREATED = "planner.plan.created"
TOOL_STARTED = "tool.execution.started"
TOOL_COMPLETED = "tool.execution.completed"
TOOL_FAILED = "tool.execution.failed"
REFLECTION_STARTED = "reflection.started"
REFLECTION_COMPLETED = "reflection.completed"
REPLAN_REQUESTED = "replan.requested"
REPLAN_COMPLETED = "replan.completed"
MEMORY_UPDATED = "memory.updated"
